# Netlify Configuration File
# Disable automatic builds and deploys on git push (Closes #4)

[build]
  command = "exit 0"
  publish = ""
  ignore = "exit 0"

[context.production]
  ignore = "exit 0"

[context.deploy-preview]
  ignore = "exit 0"

[context.branch-deploy]
  ignore = "exit 0"

